Milestone #1: Calculator
lucasmazo32/calculator pull request #1
Opened 2020-04-23 17:27 UTC by lucasmazo32

2020-04-23 19:11 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED 

Hi @lucasmazo32 good job setting this up it looks good for a start just a few changes to be made :slightly_smiling_face:  
- Add the prop-types package as a dependency ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/section/propTypes.png)

Please make changes and submit for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :world_map:

2020-04-23 19:11 UTC, Oghenebrume50 commented on package.json
> +    "big.js": "^5.2.2",
Bg.js should not be a dev dependencies

2020-04-23 19:23 UTC, lucasmazo32 commented
- Made the changes in the dependencies.

2020-04-24 02:47 UTC, MauricioRobayo approved these changes
Great, thanks for taking care of the previous issues.

Looks good, please move on 👍 .

Status: __Approved__.

2020-04-24 14:41 UTC, merged